name: Build Latest

on: 
  push:
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Set up Maven 3.9.8
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.8
      - name: Build
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: mvn clean verify
